/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.veterinaria.vista;

import com.mycompany.veterinaria.vista.insertar.*;
import com.mycompany.veterinaria.vista.consultar.Consultar;
import com.mycompany.veterinaria.vista.modificar.*;
import com.mycompany.veterinaria.vista.eliminar.Eliminar;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Hernánez Vázquez Bryan, Montalvo Pérez Jonathan, Peña Reynoso Jesús
 */
public class Entidad extends javax.swing.JFrame
{

    private boolean bandera;
    public static int consulta;
    public static int eliminar;

    /**
     * Creates new form Entidad
     */
    public Entidad()
    {
        bandera = true;
        consulta = 0;
        eliminar = 0;
        this.setContentPane(new ImagenFondo());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        combo_Tablas = new javax.swing.JComboBox<>();
        btn_Aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entidad");
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
        });

        combo_Tablas.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        combo_Tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cita", "Consultas", "Empleados", "Inventario", "Mascota", "Proveedores", "Tipo de Servicio", "Tutor", "Ventas", "Despidos" }));

        btn_Aceptar.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.setContentAreaFilled(false);
        btn_Aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Aceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptarM.png"))); // NOI18N
        btn_Aceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        btn_Aceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(combo_Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_AceptarActionPerformed
    {//GEN-HEADEREND:event_btn_AceptarActionPerformed
        // TODO add your handling code here:
        bandera = false;
        LookandFeelFrames.lFMint();
        SwingUtilities.updateComponentTreeUI(this);
        switch (Principal.accion)
        {
            case 1:
                insertar(combo_Tablas.getSelectedIndex());
                break;
            case 2:
                consultar(combo_Tablas.getSelectedIndex());
                break;
            case 3:
                modificar(combo_Tablas.getSelectedIndex());
                break;
            case 4:
                eliminar(combo_Tablas.getSelectedIndex());
                break;
            default:
                JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR 00" + Principal.accion, "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
        this.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:
        Principal.accion = 0;
        if (bandera)
        {
            Principal.activarBotones();
        }
    }//GEN-LAST:event_formWindowClosed

    private void insertar(int entidad)
    {
        switch (entidad)
        {
            case 0:
                FormCita cita = new FormCita();
                cita.setVisible(true);
                break;
            case 1:
                FormConsultas consultas = new FormConsultas();
                consultas.setVisible(true);
                break;
            case 2:
                FormEmpleados empleados = new FormEmpleados();
                empleados.setVisible(true);
                break;
            case 3:
                FormInventario inventario = new FormInventario();
                inventario.setVisible(true);
                break;
            case 4:
                FormMascota mascota = new FormMascota();
                mascota.setVisible(true);
                break;
            case 5:
                FormProveedores proveedores = new FormProveedores();
                proveedores.setVisible(true);
                break;
            case 6:
                FormTipoDeServicio tServicio = new FormTipoDeServicio();
                tServicio.setVisible(true);
                break;
            case 7:
                FormTutor tutor = new FormTutor();
                tutor.setVisible(true);
                break;
            case 8:
                FormVentas ventas = new FormVentas();
                ventas.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR 10" + Principal.accion, "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }

    private void consultar(int entidad)
    {
        consulta = entidad + 1;
        Consultar consultar = new Consultar();
        consultar.setVisible(true);
    }

    private void modificar(int entidad)
    {
        switch (entidad)
        {
            case 0:
                ModifCita cita = new ModifCita();
                cita.setVisible(true);
                break;
            case 1:
                ModifConsultas consultas = new ModifConsultas();
                consultas.setVisible(true);
                break;
            case 2:
                ModifEmpleados empleados = new ModifEmpleados();
                empleados.setVisible(true);
                break;
            case 3:
                ModifInventario inventario = new ModifInventario();
                inventario.setVisible(true);
                break;
            case 4:
                ModifMascota mascota = new ModifMascota();
                mascota.setVisible(true);
                break;
            case 5:
                ModifProveedores proveedores = new ModifProveedores();
                proveedores.setVisible(true);
                break;
            case 6:
                ModifTipoDeServicio tServicio = new ModifTipoDeServicio();
                tServicio.setVisible(true);
                break;
            case 7:
                ModifTutor tutor = new ModifTutor();
                tutor.setVisible(true);
                break;
            case 8:
                ModifVentas ventas = new ModifVentas();
                ventas.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR 20" + Principal.accion, "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }

    private void eliminar(int entidad)
    {
        eliminar = entidad + 1;
        Eliminar elimina = new Eliminar();
        elimina.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Entidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Entidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Entidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Entidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Entidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JComboBox<String> combo_Tablas;
    // End of variables declaration//GEN-END:variables

    public class ImagenFondo extends JPanel
    {

        @Override
        public void paint(Graphics g)
        {
            //ImageIcon fondo = new ImageIcon(getClass().getResource("/imagenes/fondo1.png"));
            ImageIcon fondo = new ImageIcon(getClass().getResource("/imagenes/fondo2.png"));
            g.drawImage(fondo.getImage(), 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
