/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.veterinaria.vista;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Hernánez Vázquez Bryan, Montalvo Pérez Jonathan, Peña Reynoso Jesús
 */
public class Principal extends javax.swing.JFrame
{

    public static int accion;
    public static int cadenaConsulta;
    public static int cadenaEmpleado;
    public static int cadenaInventario;
    public static int cadenaMascota;
    public static int cadenaProveedor;
    public static int cadenaTipoDeServicio;
    public static int cadenaTutor;

    /**
     * Creates new form Principal
     */
    public Principal()
    {
        accion = 0;
        cadenaConsulta = 0;
        cadenaEmpleado = 0;
        cadenaInventario = 0;
        cadenaMascota = 0;
        cadenaProveedor = 0;
        cadenaTipoDeServicio = 0;
        cadenaTutor = 0;
        this.setContentPane(new ImagenFondo());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btn_CerrarSesion = new javax.swing.JButton();
        btn_InsertarIcono = new javax.swing.JButton();
        btn_ConsultarIcono = new javax.swing.JButton();
        btn_ModificarIcono = new javax.swing.JButton();
        btn_EliminarIcono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veterinaria vet");

        btn_CerrarSesion.setBackground(new java.awt.Color(51, 51, 51));
        btn_CerrarSesion.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn_CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_CerrarSesion.setText("Cerrar Sesión");
        btn_CerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_CerrarSesion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_CerrarSesionActionPerformed(evt);
            }
        });

        btn_InsertarIcono.setBackground(new java.awt.Color(255, 153, 51));
        btn_InsertarIcono.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btn_InsertarIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/insertar.png"))); // NOI18N
        btn_InsertarIcono.setText("Insertar");
        btn_InsertarIcono.setToolTipText("");
        btn_InsertarIcono.setContentAreaFilled(false);
        btn_InsertarIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_InsertarIcono.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/insertarM.png"))); // NOI18N
        btn_InsertarIcono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/insertar.png"))); // NOI18N
        btn_InsertarIcono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_InsertarIcono.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_InsertarIconoActionPerformed(evt);
            }
        });

        btn_ConsultarIcono.setBackground(new java.awt.Color(0, 51, 102));
        btn_ConsultarIcono.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btn_ConsultarIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        btn_ConsultarIcono.setText("Consultar");
        btn_ConsultarIcono.setContentAreaFilled(false);
        btn_ConsultarIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ConsultarIcono.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultarM.png"))); // NOI18N
        btn_ConsultarIcono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        btn_ConsultarIcono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ConsultarIcono.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_ConsultarIconoActionPerformed(evt);
            }
        });

        btn_ModificarIcono.setBackground(new java.awt.Color(102, 255, 153));
        btn_ModificarIcono.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btn_ModificarIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btn_ModificarIcono.setText("Modificar");
        btn_ModificarIcono.setContentAreaFilled(false);
        btn_ModificarIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ModificarIcono.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarM.png"))); // NOI18N
        btn_ModificarIcono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btn_ModificarIcono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ModificarIcono.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_ModificarIconoActionPerformed(evt);
            }
        });

        btn_EliminarIcono.setBackground(new java.awt.Color(102, 204, 255));
        btn_EliminarIcono.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btn_EliminarIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_EliminarIcono.setText("Eliminar");
        btn_EliminarIcono.setContentAreaFilled(false);
        btn_EliminarIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_EliminarIcono.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarM.png"))); // NOI18N
        btn_EliminarIcono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_EliminarIcono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_EliminarIcono.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_EliminarIconoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ModificarIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_InsertarIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_ConsultarIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_EliminarIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btn_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_InsertarIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ConsultarIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_EliminarIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ModificarIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btn_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertarIconoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_InsertarIconoActionPerformed
    {//GEN-HEADEREND:event_btn_InsertarIconoActionPerformed
        // TODO add your handling code here:
        accion = 1;
        Entidad e = new Entidad();
        e.setVisible(true);
    }//GEN-LAST:event_btn_InsertarIconoActionPerformed

    private void btn_ConsultarIconoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_ConsultarIconoActionPerformed
    {//GEN-HEADEREND:event_btn_ConsultarIconoActionPerformed
        // TODO add your handling code here:
        accion = 2;
        Entidad e = new Entidad();
        e.setVisible(true);
    }//GEN-LAST:event_btn_ConsultarIconoActionPerformed

    private void btn_ModificarIconoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_ModificarIconoActionPerformed
    {//GEN-HEADEREND:event_btn_ModificarIconoActionPerformed
        // TODO add your handling code here:
        accion = 3;
        Entidad e = new Entidad();
        e.setVisible(true);
    }//GEN-LAST:event_btn_ModificarIconoActionPerformed

    private void btn_EliminarIconoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_EliminarIconoActionPerformed
    {//GEN-HEADEREND:event_btn_EliminarIconoActionPerformed
        // TODO add your handling code here:
        accion = 4;
        Entidad e = new Entidad();
        e.setVisible(true);
    }//GEN-LAST:event_btn_EliminarIconoActionPerformed

    private void btn_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_CerrarSesionActionPerformed
    {//GEN-HEADEREND:event_btn_CerrarSesionActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_CerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CerrarSesion;
    private javax.swing.JButton btn_ConsultarIcono;
    private javax.swing.JButton btn_EliminarIcono;
    private javax.swing.JButton btn_InsertarIcono;
    private javax.swing.JButton btn_ModificarIcono;
    // End of variables declaration//GEN-END:variables

    public class ImagenFondo extends JPanel
    {

        @Override
        public void paint(Graphics g)
        {
            //ImageIcon fondo = new ImageIcon(getClass().getResource("/imagenes/fondo1.png"));
            ImageIcon fondo = new ImageIcon(getClass().getResource("/imagenes/fondo2.png"));
            g.drawImage(fondo.getImage(), 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
