/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.veterinaria.vista.modificar;

import com.mycompany.veterinaria.modelo.Cita;
import com.mycompany.veterinaria.modelo.Consultas;
import com.mycompany.veterinaria.modelo.Mascota;
import com.mycompany.veterinaria.modelo.TipoDeServicio;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hernánez Vázquez Bryan, Montalvo Pérez Jonathan, Peña Reynoso Jesús
 */
public class ModifCita extends javax.swing.JFrame
{

    /**
     * Creates new form ModifCita
     */
    public ModifCita()
    {
        initComponents();
        llenarCombo_IdCita();
        llenarCombo_TipoServicio();
        llenarCombo_Mascota();
        llenarCombo_Consultas();
        combo_Cita.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel0 = new javax.swing.JLabel();
        combo_Cita = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo_Servicio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combo_Mascota = new javax.swing.JComboBox<>();
        txt_idtutor = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combo_Consulta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        elegirFecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        combo_horas = new javax.swing.JComboBox();
        combo_Minutos = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        btn_Modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Cita");

        jLabel0.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel0.setText("Seleccione la Cita a editar: ");

        combo_Cita.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        combo_Cita.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                combo_CitaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Seleccione los campos que desea modificar: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Seleccione el servicio: ");

        combo_Servicio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Seleccione a la mascota:  ");

        combo_Mascota.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        combo_Mascota.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                combo_MascotaActionPerformed(evt);
            }
        });

        txt_idtutor.setEditable(false);
        txt_idtutor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_idtutor.setToolTipText("idtutor");

        txt_nombre.setEditable(false);
        txt_nombre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_nombre.setToolTipText("Nombre de la mascota");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Seleccione la consulta:  ");

        combo_Consulta.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Seleccione la fecha: ");

        elegirFecha.setDateFormatString("dd/MM/yy");
        elegirFecha.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Seleccione la hora:  ");

        combo_horas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        combo_horas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "21", "22", "23" }));

        combo_Minutos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        combo_Minutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.setText(":");

        btn_Modificar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_Modificar.setText("Modificar");
        btn_Modificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_ModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_Mascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_idtutor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_Consulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(elegirFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(combo_Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(combo_Cita, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Cita, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Mascota, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idtutor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(elegirFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_horas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_MascotaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_combo_MascotaActionPerformed
    {//GEN-HEADEREND:event_combo_MascotaActionPerformed
        // TODO add your handling code here:
        Mascota mascota = (Mascota) combo_Mascota.getSelectedItem();
        txt_idtutor.setText(String.valueOf(mascota.getIdtutor()));
        txt_nombre.setText(mascota.getNombre());
    }//GEN-LAST:event_combo_MascotaActionPerformed

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_ModificarActionPerformed
    {//GEN-HEADEREND:event_btn_ModificarActionPerformed
        // TODO add your handling code here:
        int idCita = 0;
        int idservicio = 0;
        int idmascota = 0;
        int idconsulta = 0;
        String fecha = "";
        String hora = "";

        TipoDeServicio tipoServicio = (TipoDeServicio) combo_Servicio.getSelectedItem();
        Mascota mascota = (Mascota) combo_Mascota.getSelectedItem();
        Consultas consultas = (Consultas) combo_Consulta.getSelectedItem();
        Cita cita = (Cita) combo_Cita.getSelectedItem();

        if (elegirFecha.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Favor de ingresar una fecha valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else
        {
            Date date = elegirFecha.getDate();
            long d = date.getTime();
            java.sql.Date f = new java.sql.Date(d);

            idservicio = tipoServicio.getIdservicio();
            idmascota = mascota.getIdmascota();
            idconsulta = consultas.getIdconsulta();
            fecha = f.toString().substring(8, 10) + "/" + f.toString().substring(5, 7) + "/" + f.toString().substring(2, 4);
            hora = (String) combo_horas.getSelectedItem() + "." + combo_Minutos.getSelectedItem();
            idCita = cita.getIdcita();

            Cita obj_cita = new Cita();
            int r = obj_cita.actualizar(idservicio, idmascota, idconsulta, fecha, Double.parseDouble(hora), idCita);
            if (r != 0)
            {
                JOptionPane.showMessageDialog(null, "La cita fue actualizada correctamente");
            } else
            {
                JOptionPane.showMessageDialog(null, "Ocurrio un error");
            }
        }
    }//GEN-LAST:event_btn_ModificarActionPerformed

    private void combo_CitaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_combo_CitaActionPerformed
    {//GEN-HEADEREND:event_combo_CitaActionPerformed
        // TODO add your handling code here:
        int idServicio = 0;
        int idMascota = 0;
        int idConsulta = 0;
        String fecha = "";
        double tiempo = 0.0;
        String horas = "";
        String minutos = "";
        boolean bandera = false;
        //Object nombreServicio;
        Cita cita = (Cita) combo_Cita.getSelectedItem();
        idServicio = cita.getIdservicio();
        idMascota = cita.getIdmascota();
        idConsulta = cita.getIdconsulta();
        fecha = cita.getFecha();
        fecha = fecha.toString().substring(8, 10) + "/" + fecha.toString().substring(5, 7) + "/" + fecha.toString().substring(2, 4);
        tiempo = cita.getHora();

        for (int i = 0; i < combo_Servicio.getItemCount(); i++)//4 de momento
        {
            combo_Servicio.setSelectedIndex(i);
            TipoDeServicio servicio = (TipoDeServicio) combo_Servicio.getSelectedItem();
            if (servicio.getIdservicio() == idServicio)
            {
                /*nombreServicio = servicio.getNombre();
                System.out.println(""+i);*/
                break;
            }
        }

        for (int i = 0; i < combo_Mascota.getItemCount(); i++)
        {
            combo_Mascota.setSelectedIndex(i);
            Mascota mascota = (Mascota) combo_Mascota.getSelectedItem();
            if (mascota.getIdmascota() == idMascota)
            {
                break;
            }
        }

        for (int i = 0; i < combo_Consulta.getItemCount(); i++)
        {
            combo_Consulta.setSelectedIndex(i);
            Consultas consultas = (Consultas) combo_Consulta.getSelectedItem();
            if (consultas.getIdconsulta() == idConsulta)
            {
                break;
            }
        }

        try
        {
            SimpleDateFormat fechaParseada = new SimpleDateFormat("dd/MM/yy");
            Date fechaFormateada = fechaParseada.parse(fecha);
            elegirFecha.setDate(fechaFormateada);
        } catch (ParseException ex)
        {
            Logger.getLogger(ModifCita.class.getName()).log(Level.SEVERE, null, ex);
        }

        horas = String.valueOf((int) tiempo);
        switch (horas)
        {
            case "0":
                horas = "00";
                break;
            case "1":
                horas = "01";
                break;
            case "2":
                horas = "02";
                break;
            case "3":
                horas = "03";
                break;
            case "4":
                horas = "04";
                break;
            case "5":
                horas = "05";
                break;
            case "6":
                horas = "06";
                break;
            case "7":
                horas = "07";
                break;
            case "8":
                horas = "08";
                break;
            case "9":
                horas = "09";
                break;
        }

        for (int i = 0; i < String.valueOf(tiempo).length(); i++)
        {
            if (bandera)
            {
                minutos += String.valueOf(String.valueOf(tiempo).charAt(i));
            }
            if (String.valueOf(tiempo).charAt(i) == '.')
            {
                bandera = true;
            }
        }
        switch (minutos)
        {
            case "0":
                minutos = "00";
                break;
            case "1":
                minutos = "10";
                break;
            case "2":
                minutos = "20";
                break;
            case "3":
                minutos = "30";
                break;
            case "4":
                minutos = "40";
                break;
            case "5":
                minutos = "50";
                break;
        }

        combo_horas.setSelectedItem(horas);
        combo_Minutos.setSelectedItem(minutos);
    }//GEN-LAST:event_combo_CitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ModifCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ModifCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ModifCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ModifCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ModifCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JComboBox<Cita> combo_Cita;
    private javax.swing.JComboBox<Consultas> combo_Consulta;
    private javax.swing.JComboBox<Mascota> combo_Mascota;
    private javax.swing.JComboBox combo_Minutos;
    private javax.swing.JComboBox<TipoDeServicio> combo_Servicio;
    private javax.swing.JComboBox combo_horas;
    private com.toedter.calendar.JDateChooser elegirFecha;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_idtutor;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
    public void llenarCombo_IdCita()
    {
        combo_Cita.removeAllItems();
        Cita obj_cita = new Cita();
        ArrayList listacita = obj_cita.combo_Cita();
        Iterator iter = listacita.iterator();
        while (iter.hasNext())
        {
            Cita cita = (Cita) iter.next();
            combo_Cita.addItem(cita);
        }
    }

    public void llenarCombo_TipoServicio()
    {
        combo_Servicio.removeAllItems();
        TipoDeServicio obj_servicio = new TipoDeServicio();
        ArrayList listaservicio = obj_servicio.combo_TipoDeServicio();
        Iterator iter = listaservicio.iterator();
        while (iter.hasNext())
        {
            TipoDeServicio servicio = (TipoDeServicio) iter.next();
            combo_Servicio.addItem(servicio);
        }
    }

    public void llenarCombo_Mascota()
    {
        combo_Mascota.removeAllItems();
        Mascota obj_mascota = new Mascota();
        ArrayList listamascota = obj_mascota.combo_Mascota();
        Iterator iter = listamascota.iterator();
        while (iter.hasNext())
        {
            Mascota mascota = (Mascota) iter.next();
            combo_Mascota.addItem(mascota);
        }
    }

    public void llenarCombo_Consultas()
    {
        combo_Consulta.removeAllItems();
        Consultas obj_consultas = new Consultas();
        ArrayList listaconsultas = obj_consultas.combo_Consultas();
        Iterator iter = listaconsultas.iterator();
        while (iter.hasNext())
        {
            Consultas consultas = (Consultas) iter.next();
            combo_Consulta.addItem(consultas);
        }
    }
}
