/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.veterinaria.vista.insertar;

import com.mycompany.veterinaria.modelo.Cita;
import com.mycompany.veterinaria.modelo.Consultas;
import com.mycompany.veterinaria.modelo.Mascota;
import com.mycompany.veterinaria.modelo.TipoDeServicio;
import com.mycompany.veterinaria.vista.Principal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Hernánez Vázquez Bryan, Montalvo Pérez Jonathan, Peña Reynoso Jesús
 */
public class FormCita extends javax.swing.JFrame
{

    /**
     * Creates new form FormCita
     */
    public FormCita()
    {
        Principal.cadenaTipoDeServicio = 1;
        Principal.cadenaMascota = 0;
        Principal.cadenaConsulta = 1;
        initComponents();
        llenarCombo_TipoServicio();
        llenarCombo_Mascota();
        llenarCombo_Consultas();
        combo_Mascota.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        combo_Servicio = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        combo_Mascota = new javax.swing.JComboBox<>();
        txt_idtutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_Consulta = new javax.swing.JComboBox<>();
        elegirFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_horas = new javax.swing.JComboBox();
        combo_Minutos = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        btn_Insertar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar Cita");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Seleccione el servicio: ");

        combo_Servicio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Seleccione a la mascota:  ");

        combo_Mascota.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        combo_Mascota.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                combo_MascotaActionPerformed(evt);
            }
        });

        txt_idtutor.setEditable(false);
        txt_idtutor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_idtutor.setToolTipText("idtutor");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Seleccione la consulta:  ");

        combo_Consulta.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        elegirFecha.setDateFormatString("dd/MM/yy");
        elegirFecha.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Seleccione la fecha: ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Seleccione la hora:  ");

        combo_horas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        combo_horas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "21", "22", "23" }));

        combo_Minutos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        combo_Minutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.setText(":");

        btn_Insertar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_Insertar.setText("Insertar");
        btn_Insertar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_InsertarActionPerformed(evt);
            }
        });

        txt_nombre.setEditable(false);
        txt_nombre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_nombre.setToolTipText("Nombre de la mascota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_Mascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_idtutor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_Consulta, 0, 360, Short.MAX_VALUE)
                            .addComponent(elegirFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(combo_Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Mascota, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idtutor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(elegirFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_horas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_InsertarActionPerformed
    {//GEN-HEADEREND:event_btn_InsertarActionPerformed
        // TODO add your handling code here:
        int idservicio = 0;
        int idmascota = 0;
        int idconsulta = 0;
        String fecha = "";
        String hora = "";
        TipoDeServicio tipoServicio = (TipoDeServicio) combo_Servicio.getSelectedItem();
        Mascota mascota = (Mascota) combo_Mascota.getSelectedItem();
        Consultas consultas = (Consultas) combo_Consulta.getSelectedItem();
        if (elegirFecha.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Favor de ingresar una fecha valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else
        {
            Date date = elegirFecha.getDate();
            long d = date.getTime();
            java.sql.Date f = new java.sql.Date(d);

            idservicio = tipoServicio.getIdservicio();
            idmascota = mascota.getIdmascota();
            idconsulta = consultas.getIdconsulta();
            fecha = f.toString().substring(8, 10) + "/" + f.toString().substring(5, 7) + "/" + f.toString().substring(2, 4);
            hora = (String) combo_horas.getSelectedItem() + "." + combo_Minutos.getSelectedItem();

            Cita obj_cita = new Cita();
            int r = obj_cita.insertar(idservicio, idmascota, idconsulta, fecha, Double.parseDouble(hora));
            if (r != 0)
            {
                JOptionPane.showMessageDialog(null, "La cita fue registrada correctamente");
            } else
            {
                JOptionPane.showMessageDialog(null, "Ocurrio un error");
            }
        }
    }//GEN-LAST:event_btn_InsertarActionPerformed

    private void combo_MascotaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_combo_MascotaActionPerformed
    {//GEN-HEADEREND:event_combo_MascotaActionPerformed
        // TODO add your handling code here:
        Mascota mascota = (Mascota) combo_Mascota.getSelectedItem();
        txt_idtutor.setText(String.valueOf(mascota.getIdtutor()));
        txt_nombre.setText(mascota.getNombre());
    }//GEN-LAST:event_combo_MascotaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:
        Principal.activarBotones();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FormCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FormCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FormCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FormCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FormCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Insertar;
    private javax.swing.JComboBox<Consultas> combo_Consulta;
    private javax.swing.JComboBox<Mascota> combo_Mascota;
    private javax.swing.JComboBox combo_Minutos;
    private javax.swing.JComboBox<TipoDeServicio> combo_Servicio;
    private javax.swing.JComboBox combo_horas;
    private com.toedter.calendar.JDateChooser elegirFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_idtutor;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
public void llenarCombo_TipoServicio()
    {
        combo_Servicio.removeAllItems();
        TipoDeServicio obj_servicio = new TipoDeServicio();
        ArrayList listaservicio = obj_servicio.combo_TipoDeServicio();
        Iterator iter = listaservicio.iterator();
        while (iter.hasNext())
        {
            TipoDeServicio servicio = (TipoDeServicio) iter.next();
            combo_Servicio.addItem(servicio);
        }
    }

    public void llenarCombo_Mascota()
    {
        combo_Mascota.removeAllItems();
        Mascota obj_mascota = new Mascota();
        ArrayList listamascota = obj_mascota.combo_Mascota();
        Iterator iter = listamascota.iterator();
        while (iter.hasNext())
        {
            Mascota mascota = (Mascota) iter.next();
            combo_Mascota.addItem(mascota);
        }
    }

    public void llenarCombo_Consultas()
    {
        combo_Consulta.removeAllItems();
        Consultas obj_consultas = new Consultas();
        ArrayList listaconsultas = obj_consultas.combo_Consultas();
        Iterator iter = listaconsultas.iterator();
        while (iter.hasNext())
        {
            Consultas consultas = (Consultas) iter.next();
            combo_Consulta.addItem(consultas);
        }
    }
}
