/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.veterinaria.vista.consultar;

import com.mycompany.veterinaria.modelo.*;
import com.mycompany.veterinaria.vista.Entidad;
import com.mycompany.veterinaria.vista.Principal;
import javax.swing.JOptionPane;

/**
 *
 * @author Hernánez Vázquez Bryan, Montalvo Pérez Jonathan, Peña Reynoso Jesús
 */
public class Consultar extends javax.swing.JFrame
{

    /**
     * Creates new form Consultar
     */
    public Consultar()
    {
        initComponents();
        jScrollPane1.setVisible(false);
        datos.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
        });

        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "ID", "ID", "ID", "ID"
            }
        ));
        jScrollPane1.setViewportView(datos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowActivated
    {//GEN-HEADEREND:event_formWindowActivated
        // TODO add your handling code here:
        Principal.desactivarBotones();
        switch (Entidad.consulta)
        {
            case 1:
                Cita obj_cita = new Cita();
                datos.setModel(obj_cita.consultar());
                this.setTitle("Consulta Cita");
                break;
            case 2:
                Consultas obj_consultas = new Consultas();
                datos.setModel(obj_consultas.consultar());
                this.setTitle("Consulta Consultas");
                break;
            case 3:
                Empleados obj_empleados = new Empleados();
                datos.setModel(obj_empleados.consultar());
                this.setTitle("Consulta Empleados");
                break;
            case 4:
                Inventario obj_inventario = new Inventario();
                datos.setModel(obj_inventario.consultar());
                this.setTitle("Consulta Inventario");
                break;
            case 5:
                Mascota obj_mascota = new Mascota();
                datos.setModel(obj_mascota.consultar());
                this.setTitle("Consulta Mascota");
                break;
            case 6:
                Proveedores obj_proveedores = new Proveedores();
                datos.setModel(obj_proveedores.consultar());
                this.setTitle("Consulta Proveedores");
                break;
            case 7:
                TipoDeServicio obj_tipoDeServicio = new TipoDeServicio();
                datos.setModel(obj_tipoDeServicio.consultar());
                this.setTitle("Consulta TipoDeServicio");
                break;
            case 8:
                Tutor obj_tutor = new Tutor();
                datos.setModel(obj_tutor.consultar());
                this.setTitle("Consulta Tutor");
                break;
            case 9:
                Ventas obj_ventas = new Ventas();
                datos.setModel(obj_ventas.consultar());
                this.setTitle("Consulta Ventas");
                break;
            case 10:
                Despidos obj_despidos = new Despidos();
                datos.setModel(obj_despidos.consultar());
                this.setTitle("Consulta Despidos");
                break;
            default:
                JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR 3" + Principal.accion, "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
        jScrollPane1.setVisible(true);
        datos.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:
        Entidad.consulta = 0;
        Principal.activarBotones();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable datos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
